# Generated by Django 4.0.3 on 2022-04-03 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crycoin', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
